SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [stg].[stpOM_Metas_SYM_COMPANY]
AS BEGIN

-- DELETO A MINHA TABELA TEMPORARIA
	IF(OBJECT_ID('BI_Staging.stg.temp_OM_Metas') IS NOT NULL) 
		DROP TABLE BI_Staging.stg.temp_OM_Metas

-- AQUI ELE PEGA OS DADOS DA BASE DE DADOS EM PRODUÇÃO E COLOCA-OS EM UMA TABELA TEMPORÁRIA
SELECT 
	 DATA
	,COD_CENTRO_CUSTO
	,CONTA_REDUZIDA
	,META
	,'SYM_COMPANY' AS ORIGEM
INTO stg.temp_OM_Metas
FROM PROD.dbo.OM_Metas_SYM_COMPANY

-- GARANTE QUE A TABELA DESTINO NO BI_STAGING ESTEJA LIMPA
TRUNCATE TABLE [stg].[OM_Metas_SYM_COMPANY]

-- GARANTINDO QUE ESTÁ LIMPO, INSERIMOS TODOS OS DADOS NOVAMENTE, A PARTIR DA TABELA TEMPORARIA
INSERT INTO [stg].[OM_Metas_SYM_COMPANY]
SELECT * FROM stg.temp_OM_Metas

-- DELETO A MINHA TABELA TEMPORARIA
	IF(OBJECT_ID('BI_Staging.stg.temp_OM_Metas') IS NOT NULL) 
		DROP TABLE BI_Staging.stg.temp_OM_Metas

END;

