ALTER TABLE [dbo].[OM_KCCDADOS] ADD COD_GERENTE INT


UPDATE [dbo].[OM_KCCDADOS]
	SET COD_GERENTE = '1'
	WHERE GERENTE = 'DANRLEI'

UPDATE [dbo].[OM_KCCDADOS]
	SET COD_GERENTE = '2'
	WHERE GERENTE = 'MAURICIO'
	
	UPDATE [dbo].[OM_KCCDADOS]
	SET COD_GERENTE = '3'
	WHERE GERENTE = 'LUCIO'

	UPDATE [dbo].[OM_KCCDADOS]
	SET COD_GERENTE = '4'
	WHERE GERENTE = 'MILTON'

UPDATE [dbo].[OM_KCCDADOS]
	SET COD_GERENTE = '5'
	WHERE GERENTE = 'CARLOS'


	UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '6'
	WHERE GERENTE = 'JOCIMAR'


UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '7'
	WHERE GERENTE = 'EDUARDO'

UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '8'
	WHERE GERENTE = 'ANTONIO'

	
UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '9'
	WHERE GERENTE = 'KELVIN'

	
UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '10'
	WHERE GERENTE = 'GEROMEL'

UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '11'
	WHERE GERENTE = 'ROSA'



UPDATE [dbo].OM_KCCDADOS 
	SET COD_GERENTE = '12'
	WHERE GERENTE = 'LUAN'