USE PROD

SELECT * FROM dbo.OM_SYM_COMPANY


ALTER TABLE dbo.OM_SYM_COMPANY ADD COD_DIRETOR INT



UPDATE dbo.OM_SYM_COMPANY
	SET COD_DIRETOR = 1
	WHERE DIRETOR = 'TITE'


UPDATE dbo.OM_SYM_COMPANY
	SET COD_DIRETOR = 2
	WHERE DIRETOR = 'HOMERO'

	

UPDATE dbo.OM_SYM_COMPANY
	SET COD_DIRETOR = 3
	WHERE DIRETOR = 'LAURO'



--VERIFICA SE TEM "NULL" NAS LINHAS
SELECT COD_DIRETOR FROM dbo.OM_SYM_COMPANY	WHERE COD_DIRETOR IS NULL



--VERIFICA 
SELECT DISTINCT 
	COD_DIRETOR, 
	DIRETOR 
FROM dbo.OM_SYM_COMPANY 
ORDER BY COD_DIRETOR