USE PROD

SELECT * FROM dbo.OM_SYM_COMPANY

--cod_gerente
--cod_diretor


--INSERE UMA COLUNA NA TABELA (VAZIA)
ALTER TABLE dbo.OM_SYM_COMPANY ADD COD_GERENTE INT


SELECT DISTINCT GERENTE FROM dbo.OM_SYM_COMPANY

/*GERENTE
1 - DANRLEI
2 - MAURICIO
3 - LUCIO
4 - MILTON
5 - CARLOS
6 - JOCIMAR
7 - EDUARDO
8 - ANTONIO
9 - KELVIN
10 - GEROMEL
11 - ROSA
12 - LUAN




*/

--INSERE OS DADOS NA TABELA CRIADA (COD_GERENTE)

UPDATE dbo.OM_SYM_COMPANY
	SET COD_GERENTE ='1'
	WHERE GERENTE = 'DANRLEI'

UPDATE dbo.OM_SYM_COMPANY
	SET COD_GERENTE ='2'
	WHERE GERENTE = 'MAURICIO'

UPDATE dbo.OM_SYM_COMPANY
	SET COD_GERENTE ='3'
	WHERE GERENTE = 'LUCIO'

UPDATE dbo.OM_SYM_COMPANY
	SET COD_GERENTE ='4'
	WHERE GERENTE = 'MILTON'


UPDATE dbo.OM_SYM_COMPANY
	SET COD_GERENTE ='5'
	WHERE GERENTE = 'CARLOS'

UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '6'
	WHERE GERENTE = 'JOCIMAR'


UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '7'
	WHERE GERENTE = 'EDUARDO'

UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '8'
	WHERE GERENTE = 'ANTONIO'

	
UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '9'
	WHERE GERENTE = 'KELVIN'

	
UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '10'
	WHERE GERENTE = 'GEROMEL'

UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '11'
	WHERE GERENTE = 'ROSA'


UPDATE [dbo].OM_SYM_COMPANY 
	SET COD_GERENTE = '12'
	WHERE GERENTE = 'LUAN'



--VERIFICA SE TEM "NULL" NAS LINHAS
SELECT COD_GERENTE FROM dbo.OM_SYM_COMPANY	WHERE COD_GERENTE IS NULL



--VERIFICA 
SELECT DISTINCT 
	COD_GERENTE, 
	GERENTE 
FROM dbo.OM_SYM_COMPANY 
ORDER BY COD_GERENTE