CREATE TABLE [stg].[receitas](
	[COD_ORGAO_SUPERIOR] [VARCHAR] (10),
	[NOME_ORGAO_SUPERIOR] [VARCHAR] (100) ,
	[COD_ORGAO] [VARCHAR] (10) ,
	[NOME_ORGAO] [nvarchar](255) ,
	[COD_UNIDADE_GESTORA] [VARCHAR] (10) ,
	[NOME_UNIDADE_GESTORA] [nvarchar](255),
	[CATEGORIA_ECONOMICA] [nvarchar](255) ,
	[ORIGEM_RECEITA] [nvarchar](255),
	[ESPECIE_RECEITA] [nvarchar](255),
	[DETALHAMENTO] [nvarchar](255),
	[VALOR_PREVISTO] [FLOAT],
	[VALOR_LANCADO][FLOAT],
	[VALOR_REALIZADO][FLOAT],
	[PERCENTUAL_REALIZADO][FLOAT],
	[DATA_LANCAMENTO] [DATE],
	[ANO][VARCHAR] (50))


